### ISSUE TITLE
No Clean Way to Check whether a Job is Terminated

### ISSUE THREAD

**Issue by AlexanderNenninger** [nakanocs/abs2WebAPI#1]
As far as I can tell, the ABS2WebAPI does not provide a simple way of determinig if a job is terminated. A `terminated` field is not part of any response, that can be obtained by calling the route `https://qubosolver.cs.hiroshima-u.ac.jp/v1/jobs`.

On the other hand, if one submits a job, and then immediately requests the corresponding solution, one may reiceve a response with status code `202` and the message `'[<JOBNAME>] does not exist'`. Waiting a few seconds alleviates this. One recieves a response with status code `200` as described in the [manual](https://github.com/nakanocs/ABS2WebAPI/blob/main/WebAPI_manual.md#getting-a-solution).

Handling would be simplified, if the information, whether a job is finished, was part of the jobs API.

**Comment by nakanocs** [comment]
Thanks for the comments.

I designed the Web API so that directory "jobs" (https://qubosolver.cs.hiroshima-u.ac.jp/v1/jobs)  is a hot holder.
So I do not want the QUBO solver to update job files in the "jobs".

If job files are uploaded in the directory "jobs", they are queued for processing.
The QUBO solver selects the oldest job file in "jobs", and moves it to "solutions" (https://qubosolver.cs.hiroshima-u.ac.jp/v1/solutions).
The QUBO solver works for solving the QUBO problem specified by the job file, and the results (including intermediate solutions) are overwritten in the job file (or solution file) in "solutions".

So, you can determine if the QUBO solver start a job and if it teminates as follows:
1. A job is started if the job file is removed from the directory "jobs".
2. The QUBO solver is currently working for the job, if the solution file in "solutions" does not have key "terminated" or has key "terminated" with value false.
3. The QUBO solver is terminated for the job if the solution file has key "terminated" with value true.

**Comment by AlexanderNenninger** [comment]
Thanks for your clarifications. So from a user's perspective the procedure would be as follows:
 1. Submit job
 2. Confirm job was accepted
 3. Periodically (e.g. with exponential backoff) check whether solution exists and has the field "terminated" set to true.

**Comment by nakanocs** [comment]
Yes, the Web API is RESTFUL and users must periodically access files in directories (or resources in server) to see the current status.
